username: darrenptran@gmail.com
password: uc$Duke1214

positions:
- Python

locations:
- United States

uploads:
 Resume: /mnt/win/Users/trand/OneDrive/Desktop/CV/DarrenTran-BootCampGrad-Resume.pdf
# Cover Letter: # PATH TO cover letter
# Photo: # PATH TO photo

#output_filename:
#- PATH TO OUTPUT FILE (default output.csv)

blacklist:
- Mindlance
- Cook Systems
-

blackListTitles:
- AR
- Mulesoft
- Big Data
- VR
- Manager
- Lead
- Principal
- Founding
- Embedded
- Java
- Angular
- Hadoop
- MongDB
- Spark
- Ruby
- Rails
- Azure
- GCP
- .Net
- .NET
- Senior
- Sr.
- Embedded
- PHP
- iOS
- Android
- Swift
- Salesforce
- Tableau
- Mobile
- Controls
- API
- C#
- C++
- C
- Golang
- TypeScript
- Security
- Network
- Warehouse
- Pipeline
- Prototype
- Client
- Growth
- Hacker
- Unpaid
- Report
- Clearance
- PhD
- Minimum
- Cybersecurity
- Instructor
- Teacher
- Volunteer
- Student
- Sales
- ServiceNow

keyword_list:
- Python
- Engineer
- Developer
- Researcher
- Scientist
- Programmer
- Analyst

avoid_list:
- 3+ year
- 3 year
- 3+ yr
- 3 yr
- 4+ year
- 4 year
- 4+ yr
- 4 yr
- 5+ year
- 5 year
- 5+ yr
- 5 yr
- 6+ year
- 6 year
- 6+ yr
- 6 yr
- 7+ year
- 7 year
- 7+ yr
- 7 yr
- 8+ year
- 8 year
- 8+ yr
- 8 yr
- 9+ year
- 9 year
- 9+ yr
- 9 yr
- 10+ year
- 10 year
- 10+ yr
- 10 yr
